apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: database-connection-secret
spec:
  encryptedData:
"    MONGO_URI": "AgArsxbVOMZ/4rQASQjDpjpTrb8nwHUMGgPswghPHmySUDY8LB2E3ihcwU6IxLFM14u0PhvI3Fj9B+nvRyzBo5+TNZirvtwEvvXlPT7e5aeRz6EgrbgjUv5llB9fMk9W2OzywRihrhijd8yhVs9DGg3iyTdgEQvBTNj8ex1wZY7H35OAwB6gmJMxBvNJk/7uS4WQDxls9lfVaJMasfthzfkMTwOg6lC6SEJVyivv88rgvDP+wYfzhRMCVk5hpsVt93V8QJKkgf1dx8jixt+lb9v1bZiu7N6G3sLzBIvS2PkLPqiphgf7A7gIxmjb4hma9SS3Gm2+L2UUh0S6KoYYG1bnc4XanBLMRmLYO9JwPTy1S26arCaQvvcU6dIBG1WsOAiiySVqxlnpynFDBgAlBfpIKSPffjKIOBFLnaK3aFqqY5IdfZYyiKGtXudXDE8sTgB5tWnn+c7YrVoLNtnaqimzFLxW9BHP7d0h/7v1yD/owE3k0+bDWinKYMvYJzHXngLqSz3ZmF6fN61iUZk0WSo7vdCfg2nbqG/iGG2w83ZHGx5neg2qjIPIbtZuy1Mfu4V1JgUN4ScjgeCr4Uo3la145sP0nHov/LJzjpL5WQ+dHl/mFDE9Cpgj433gh+4y09gH3TOxF55qjoIZrHG1/9HEPauapWkzbGxr/sevs3Jc3yfqvnzbOm0t1gulZUL/lNjx6aRUA/2WGFbxWJ4Vf9tBb+KNTC/ATwMQKUR3PKB58xrIavzWjtK6EEogcmX2vxi/UqcNn215xPn4gDOvlOd30LjstJSN0cSj85DWpO//Y0+Mtm3s6MO+9vexFI42ZGReyPcrrUb3TMbrxRvWu6Ey5pc3"
  template:
    type: Opaque
