apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pull-secret
spec:
  encryptedData:
    ".dockerconfigjson": "AgDVTrsZbf6fWqAhX224AVWxv0OvQp2S4ap1DZkhnZxRR60lGxYWGtAH33wETmUtSWQYH9RrkF6jOlZ69v1i/wD/tQyBv7cQ26/eiwFai/wxbRaycuZchCoYTS4UarFw1bIT9zEB5OpO2mL3s2Nr6Q5ZHkpwaLvDpnRSqccypqJ+B5ullZQ22Ua+i26CbPYYoVnc1UZ1+oUn88qmarXZuCjFviesLA+TANFJu76bSBPWjBy7piWEEpWzXVmFvFqEOg+4EER4u6k5YOjXB5oHFZOOu/eO/PfRK34XcODfmH8xrahX/0ZU/NVbQJphmO9/3Zl19/uYkmwiLHqMS3ENYSKJQ6R9wWIoi7lrx+LrGvhhjnDYMIlTEFdVyh2F50jLxwh6bfBNumnOZOKLKgiEVDRjX3jRx7h6NjON4nE2ffmm4d9upxg5Vmv1D/CiMpIUpFPG2PlSWYpy3sRWcImK2jhK19OwYizS3up5iDNJuyZ3BbYtP6QP4+7ZpOr2U/VtKDWba6fAkMLYBYgSXQDLEZxWuJRTJpg2JocqkYNFZvzh1OSr7M2/rLsJ8u1fsYPhLeDySgBxen4A1ijhXdbhPwMbOt9TwEJ2OatBIwExhJc3Jz8AhwTlPf3ebTL7btbyQzAKsUUsXIcALsVLbVQDWFgK+sArcdSVdx2+59thJpjY9OlRbui+KxK4x5sMC/m44lRmXzEBbp4OCKjGF1UBreOQGbQWtsp5MGwlf0hkRidDph93YVjYumqS6L53PVWdNYFg2TR3L82cEhTwCcyuFHL2OSSYnpuPp2UnS+vIGw=="
  template:
    type: kubernetes.io/dockerconfigjson
