apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pull-secret
spec:
  encryptedData:
    ".dockerconfigjson": "AgBZxEXXbmQ+Wb20dqiA1/QBGUlFDVRr9xL603eS/zJ+Pwntz8ok1QDdUQ+5hgPva9R0um5FsXvwr1wX0ckOuLp0OMJMPhPYtixfTDQ0z4fTieUnSP1dG39reWaH3kZzhdvHP6313qhvtiW2iLPHCpC5BzZ84rTUomdexGLmFr4TY8+SNhdG5+i3hrgkOEn2XBtce9flQ1tYEvZ364YO2XfB4I4txG+57XyixSkcE49WcIUqwnf5uBdTJDIUk3oGY5LE+l+Faopdm/57tDgL+Pl2u1gUCGiSTueUJuzVvcwpk2HNRfGhFgXmgJRNsS/snwl98HLqVlAdeLRgW+h7dvBjZAaqVO9NCjskAUmMR9yongBPU3GPBbV7jAR1MuCd4xWE2Xe0crLa/GTaEW6f6P1he/B3ZJXl1JSJXm+wCAm59IeuDM1uTUIHOv/TvnbLNynIfoBxQKz3rX9we7lnlGyV0ZSoSZp3YyRcvfCehBzEOSFOpuksxG+vFHu4scgkPjZ3DW1EVD7I/SbJnooxidf7857jIRBbVwFAiIyqrNE8ypfEzO2+UjNIGBfGVKnLvXPP4tsnBWfDLgTWF5VV1RFPfmtWHtRnuJyQBZVnuju7QN6LCJ6H27DVDGq3XmGsOEMcGc7e2QJneGmpJC4Hbjafs0GizWXTVbrsHTYmF98nJSreIAv1TM9YYNbBTXJKWFGW9EdbcKWv80af3PsBe6y8U9je/Wl9/Ti+BpNeG5gQwTXRWcoI37JedNeD+eOcX1wifLH4O4lxiJ9EeGg7nzOuFQNzRl9srDL3XvgR6Q=="
  template:
    type: kubernetes.io/dockerconfigjson
