apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pull-secret
spec:
  encryptedData:
    ".dockerconfigjson": "AgBySbjxcIFMQ90usXDFQ0byx1UVZXAApQNiAsJApBHWEWnvtiryyWCCkZJn6pdpuc/Kj46kZvGT7TW3LAh0q5LYkh30+wDtYGRVoMcr5PzPbBnPAFWPhvowZKHSLDvQX8HRbMfy10m4fT0WX1P6eIAIb1PczpoIjTO1xRFxwDidczPdZlEYJjhV8XFMEmwKEvBKuYhSP74ku8CcpxterAsGOi22iOqQpRERToDo1VvGwwgra1GhLg7ufdjxKPDDVhwX9ffNXuYI5YM0Sp8RfsAfdYQ+HW8vUXNEdpeBFzBHh9QbWyESpNbXQfdEjTQHTmBnAcxZpQE9r3hN0eFICQex4q11WF4UmgPEwcOfp8OLU3N8wJsXbkr8PBYIEG0Kdo56Z6ejgorC7p7gvtZ7YNClJoByz4ZEhVmgeuy151DBsvxh6eQ9Pl4i9iT/X2hhb8x7jsD7P9H5CFQq2Uh6S3mOhlUs5NunsK6dHtW7hTfDRDK9Lxp/zbfLXMG1aM+SfI39KpiUluzW9JTQ2wI/1PHiQsNuMJHk9HHBtNfULWSOa55Jh9KdPh553ZOjMBju4dBwVNxrC56NZ0FYzt/wP7Cq9gzdaK1hQ1ia7rOk1fosV95z/HmcQFqD7Yi3/Lv7r2nRuy/wwKI+AHqTG4O/ZvfKhkn5jeqa/Cd8TwDhnH7hSGqailC4WDRMFOh2r30XxksCEo6hQTUHS0OLzQG68XzO3pWr3aL9O13dTN49n59IERzzil8FFQneGhNbfTComtgyN4Zu9q+5fXFfhd3d9vNDR6hypkazuzy/KTLlfA=="
  template:
    type: kubernetes.io/dockerconfigjson
