apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pull-secret
spec:
  encryptedData:
    .dockerconfigjson: "AgBZUdhEVUhjscDWUOnS+DddYTnHIudNGspuyhtJ8bc/JERhD7YpPkRy4MikDWHb/2qW/EzS6D/NGNM7IFaw8DqOxLrQ7JgyQblqVvhkMQdAFJqk1gzFPZtxZqH34cjLNZb2xXno456hULO6lGdugDYPhZrBBqIiUWqC5DnnVAsJCUNlTqy0FEvliQpY991DIXrmrswRjcn+UlLskDIRMG4w4k+zwWcAy8r3PegN+LpqtGTlmb+2CdOf64TPGTES91IH8PW4zjka5I21/P1HQR6oOHikz2v4yhvXDccNIfYktGLTf74d6CixjfQH/tV04WkgBlT9PXNmpTsZQDULOHPVmxiWOQlWOL0h35RuLfnTNAWctKqESCH2HJvldjHC25y8++9FvU+rgJueOYzbjLMkuLwuNMfN44BYBAXVF4oh8zHu3CcR6Z/aBF55j7UQ58v0AVsojpXBLyEvGJ7L+dc56PsFaNy5WpudrE45FMTZ8wsVB08fv39XQunQje+PauFeFsX+RmLfecdqpSmHuCMBeCKilr7As1KVhcJ56BVOXqgrSHNmbsE7XYrTDsf9jCoLwua37fEBh9csXUg8DybA0WKXoij45ep95GL7QvclWrOFNFpby3SnCGy7JP/2DcHWVlTl3nYH5K8VbxNusbGDdNAN2fXhiAkAIRwN71Q5ilUSB9y1KxZysIn6GY+3duzBiTW/i/+ayaFLUiYL1qKmSx4Xo2wGgvKIH8CLUe4Yg+1C0yCpg4t9rTkoSqkLRZw5CNTP5nP3ACa/omwdvC3qnu9qBO4YfLXRaJpc/w=="
  template:
    type: kubernetes.io/dockerconfigjson
