apiVersion: v1
kind: Service
metadata:
  name: todo-example
  labels:
    app: todo-example
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: todo-example
