apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: database-connection-secret
spec:
  encryptedData:
    "MONGO_URI": "AgBwDhwh1vPAXWDIkir1jpYgWJ/t6sFkAMyVTbXsTx/9bvxxZfOuxZ1dz4adxWbB3ZKr68ITyxZV3EaEo43LNdwsKKDfQbaxj2xGyK7jhMhYWtRdN5o3IMXYwnDmnLeAUD3fVzPwrB0pPyaHzl9rr9Fc1JHArWdiHB/6EIHIO9ydpUovmeu3e0SW/Q33NJfMbtQSN1RbAUeAIaMNIDwbH8NdrpahyDUEz2KWgoWtIXQQNkeXh1LKJCxNo9ndtXhxFjylqL/HMmp6huqC4TWI4yhUkxayCUXhgFULEV/zp2GIlQVV9BjZ1d5IlIr6I0c9+Pw5pQmpIz69crclorz267LNJgZ9g6u7jko3qxkjy09x4VQL48Cj7bRLZIlw8IBTLK1V1BJ7uiBMwAFKqXr90zqxNBGRtrYLydWYbKcx622ENcMygMpbsqJx0i9AJ6TO/cLc76lSOpCqtFQNRa4mki6TYuB2iOKiR7COOYX6ey+7DhjZRF7RLrXLYbl2LpS/IbWoFI2ImuqJXAdDMDmC7EsyDSWmHLtASDrAGxo3KKm+qtJzKTotqcepXEmgH0UdLsctqymH03G4GAUj1JUzSKQIDJ00cq7+m+8dfAnvjVtfp6cq9ZC9pjMiseoT+oAB75XulImu76/KpZkFW4h3P3okdw112+JYh72+PgeB5rLBxH7Y/bNiGRPLDVwCGnNxIGJDsba0pj9pX7193gaYrAbHVLbc3/oot/CCaD78C7rzyT48/IFuZHU8QHiTM70MDeZdwR2N5NMcyO+E/EOClsXpsaU+tyWYky9+lXUfcMTpsaIgGNwTRlSMBvEX5IESV9vu/T8ATJXd"
  template:
    type: Opaque
