apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pull-secret
spec:
  encryptedData:
.dockerconfigjson: "AgC6wq+cGbAb1viSiqyFvNCU/R9MCenr9utTjOcOYd7/m/8tF5iJGpuiv5KD9fir5PNqpWG5N1kACTmEuxdMPdS72ghYSDanh34pnzNbMf5bUjbwTUP0LbEpdS+0+76mD2gTauSXgpVlJ5aptqICzvkdx4232xmbEfHt4tQAz7zovjVnk07aXJYOchoINaLoO+WKMcJJyLL5pkyldEQYPxJGQFngSKX3Fl7u6fqQsM8e2n6SGKnPTSJNMbQ9TJUBB5Fa/fFuq7d4kvz0zuava17y5ld0gGLn3qJ1gPPf/Oz9qRr3Gy1hlPOcNkkZnKH2ZOrl82qAZ5A6vBz7lEvXcKlODR9BSWofU5EYOsEPBWQ2YfBFqxMZiaZlHzT7izB8+WQ53DXe8EMiCnH6utz0xXLegKDJJrQguVs3j1793aoUammtYYi++rZuIJCxrN+d/FbZd9yqT9wWWKdwy7iK57Hosv5EOtgTbTZWAUSOuTjODUD7+KVjdFcKkvljixPgMar0rjjSwNSKerl5E5TwpI2M2D8hbJwcriIb85UhiYh29SrJvL0L3hgF/auNYf2asO5Yl4OCQZCZNmE6Rh1Z0rxw2Fhs+MGUOoUoSwKvtO3APOEBrSsylcVlE9xhRtHZpaNsTaSjMImDao239g92MUFO1RO2iNLCnVqnZHNZOcjDaOQJueb5F7KHJXq/6SiJgUZBLS5WuUY7W3UF90NXwPD9tla9fblowYdWjcl9+wUrsdVXPTNJMfeh1uCK28B/mbrqAtb3bACqvlkKDuDG3A65r+0ixRPx0ARKsO8Gyw=="  template:
    type: kubernetes.io/dockerconfigjson
