apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: init
  namespace: argocd
spec:
  project: apps
  source:
    repoURL: git@github.com:Massfice-Premiere/argocd.git
    targetRevision: HEAD
    path: apps/init
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: standard-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: git@github.com:Massfice-Premiere/argocd.git
      revision: HEAD
      directories:
      - path: apps/standard/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:Massfice-Premiere/argocd.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
          allowEmpty: true
