apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
spec:
  sourceRepos:
    - ${REPO_URL}
  destinations:
    - namespace: '!argocd'
      server: 'https://kubernetes.default.svc'
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  clusterResourceBlacklist:
    - group: 'argoproj.io'
      kind: 'ApplicationSet'
    - group: 'argoproj.io'
      kind: 'Application'
    - group: 'argoproj.io'
      kind: 'AppProject'
