apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ${SECRET_NAME}
spec:
  encryptedData:
    %{ for key, value in yamlencode(SECRET_DATA) }
      ${key}: ${value}
    %{ endfor ~}
  template:
    type: ${SECRET_TYPE}
