apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xyz
spec:
  project: apps
  source:
    repoURL: git@github.com:massficePremiere/argocd.git
    targetRevision: HEAD
    path: xyz
  destination:
    server: https://kubernetes.default.svc
    namespace: xyz
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
