  apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: argocd-application
    namespace: argocd
  spec:
    project: apps
    source:
      repoURL: git@github.com:massficePremiere/argocd.git
      targetRevision: HEAD
      path: apps
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        selfHeal: true
        prune: true
        allowEmpty: true
