apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  sourceRepos:
    - git@github.com:Massfice-Premiere/argocd.git
  destinations:
    - namespace: 'argocd'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: 'argoproj.io'
      kind: 'ApplicationSet'
    - group: 'argoproj.io'
      kind: 'Application'
    - group: 'argoproj.io'
      kind: 'AppProject'
