apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-example
  annotations:
    configmap.reloader.stakater.com/reload: "example-config-map"
    secret.reloader.stakater.com/reload: "database-connection-secret"
spec:
  selector:
    matchLabels:
      app: todo-example
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-example
    spec:
      containers:
        - name: todo-example
          image: massfice/test-repo:b21fc7a0a775f1dbd3201f23db87ebfa3221c61b
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: example-config-map
            - secretRef:
                name: database-connection-secret
