apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-application
  metadata: argocd
spec:
  project: apps
  source:
    repoURL: {{ .Values.repo_url }}
    targetRevision: HEAD
    path: apps/argocd
    helm:
      values: |
        installCRDs: true
        createCustomResource: true
        repo_url: git@github.com:massficePremiere/argocd.git
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
