apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: argocd

patches:
  - path: app_patch.json
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: xyz
  - path: ingress_patch.json
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: ingress